name: WWW-Lipsum-Chinese
version: 0.01
abstract: Chinese Lorem Ipsum Generator
author: Kang-min Liu <gugod@gugod.org>.
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  IO::All: 0
requires:
  LWP::Simple: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
